"""add stealth attribute to dragons

Revision ID: b2256e50dd88
Revises: 99d0d30d64ae
Create Date: 2026-08-24 00:27:26.152378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2256e50dd88'
down_revision: Union[str, Sequence[str], None] = '99d0d30d64ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dragons', sa.Column('stealth', sa.Integer(), nullable=True))
    op.execute('UPDATE dragons SET stealth = 0 WHERE stealth IS NULL')
    op.alter_column('dragons', 'stealth', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dragons', 'stealth')
    # ### end Alembic commands ###
